import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/navbar/Navbar";
import Footer from "@/components/footer/Footer";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" data-theme={'dark'}>
    <body className={inter.className}>
      <div className={'app-container flex flex-col justify-between min-h-screen'}>
        <Navbar />
        <div>
          {children}
        </div>
        <Footer />
      </div>
    </body>
    </html>
  );
}
